/*
 ******************************************************************************
 * File Name    : app_radio.h
 *
 * Description  :
 * Header file for the FreeRTOS LoRa radio transmission module.
 *
 * This module provides:
 *  - Radio transmission task declarations
 *  - Radio initialization interfaces
 *  - Radio event definitions
 *  - RTOS queue declarations
 *
 * Radio Responsibilities:
 *  - LoRa payload transmission
 *  - SX126x/SubGHz radio configuration
 *  - IRQ event processing
 *  - RTOS radio synchronization
 *
 * Notes:
 *  Payload transport is interrupt-driven and synchronized
 *  through FreeRTOS queues.
 *
 * Created on : April 16, 2026
 * Author     : Jeremiah Apolista
 ******************************************************************************
 */

#ifndef INC_APP_RADIO_H_
#define INC_APP_RADIO_H_

/*****************************************************************************/
/* Includes                                                                  */
/*****************************************************************************/

#include "cmsis_os2.h"
#include "FreeRTOS.h"

#include "radio_driver.h"
#include "queue.h"

/*****************************************************************************/
/* Radio Event Definitions                                                   */
/*****************************************************************************/

/*
 * Radio event types generated by the SX126x IRQ handler.
 *
 * EVENT_TX_DONE:
 *  Payload transmission completed successfully.
 *
 * EVENT_TX_TIMEOUT:
 *  Transmission timeout occurred.
 *
 * EVENT_TX_ERROR:
 *  Transmission failed due to CRC or radio error.
 */
typedef enum
{
    EVENT_TX_DONE,
    EVENT_TX_TIMEOUT,
    EVENT_TX_ERROR

} radio_event_t;

/*****************************************************************************/
/* External Radio Variables                                                  */
/*****************************************************************************/

/*
 * SX126x packet configuration structure.
 * Stores LoRa packet configuration parameters.
 */
extern PacketParams_t packetParams;

/*****************************************************************************/
/* FreeRTOS Queue Handles                                                    */
/*****************************************************************************/

/*
 * Queue used to transfer serialized payloads
 * from the aggregator task to the radio task.
 */
extern QueueHandle_t xRadioQueue;

/*
 * Queue used to transfer radio IRQ events
 * from ISR context to the radio task.
 */
extern QueueHandle_t radioQueueHandle;

/*****************************************************************************/
/* Function Prototypes                                                       */
/*****************************************************************************/

/*
 ******************************************************************************
 * Function Name : RadioTask
 *
 * Description:
 * FreeRTOS task responsible for payload transmission
 * and radio event processing.
 *
 * Parameters:
 *  argument : Unused
 *
 * Returns:
 *  None
 ******************************************************************************
 */
void RadioTask(void *argument);

/*
 ******************************************************************************
 * Function Name : radioTx
 *
 * Description:
 * Initiates LoRa payload transmission through the SX126x radio.
 *
 * Parameters:
 *  payload : Pointer to payload buffer
 *  len     : Payload length in bytes
 *
 * Returns:
 *  None
 ******************************************************************************
 */
void radioTx(uint8_t *payload, uint8_t len);

/*
 ******************************************************************************
 * Function Name : radioInit
 *
 * Description:
 * Initializes the SX126x/SubGHz radio peripheral and
 * configures LoRa transmission parameters.
 *
 * Parameters:
 *  None
 *
 * Returns:
 *  None
 ******************************************************************************
 */
void radioInit(void);

#endif /* INC_APP_RADIO_H_ */
